package com.miracle.sharebazar.utils;

import java.util.HashMap;


public class ApplicationMaps {

	public static HashMap<String,String> CURRENCYID_COUNTRYNAME=new  HashMap<String, String>();

	
	
	
	static {
		CURRENCYID_COUNTRYNAME.put("AFA", "Afghanistan Afghani");
		CURRENCYID_COUNTRYNAME.put("ALL", "Albanian Lek");
		CURRENCYID_COUNTRYNAME.put("DZD", "Algerian Dinar");
		CURRENCYID_COUNTRYNAME.put("ARS", "Argentine Peso");
		CURRENCYID_COUNTRYNAME.put("AWG","Aruba Florin");
		CURRENCYID_COUNTRYNAME.put("AUD","Australian Dollar");
		CURRENCYID_COUNTRYNAME.put("BSD","Bahamian Dollar");
		CURRENCYID_COUNTRYNAME.put("BHD","Bahraini Dinar");
		CURRENCYID_COUNTRYNAME.put("BDT","Bangladesh Taka");
		CURRENCYID_COUNTRYNAME.put("BBD","Barbados Dollar");
		CURRENCYID_COUNTRYNAME.put("BZD","Belize Dollar");
		CURRENCYID_COUNTRYNAME.put("BMD","Bermuda Dollar");
		CURRENCYID_COUNTRYNAME.put("BTN","Bhutan Ngultrum");
		CURRENCYID_COUNTRYNAME.put("BOB","Bolivian Boliviano");
		CURRENCYID_COUNTRYNAME.put("BWP","Botswana Pula");
		CURRENCYID_COUNTRYNAME.put("BRL","Brazilian Real");
		CURRENCYID_COUNTRYNAME.put("GBP","British Pound");
		CURRENCYID_COUNTRYNAME.put("BND","Brunei Dollar");
		CURRENCYID_COUNTRYNAME.put("BIF","Burundi Franc");
		CURRENCYID_COUNTRYNAME.put("XOF","CFA Franc (BCEAO)");
		CURRENCYID_COUNTRYNAME.put("XAF","CFA Franc (BEAC)");
		CURRENCYID_COUNTRYNAME.put("KHR","Cambodia Riel");
		CURRENCYID_COUNTRYNAME.put("CAD","Canadian Dollar");
		CURRENCYID_COUNTRYNAME.put("CVE","Cape Verde Escudo");
		CURRENCYID_COUNTRYNAME.put("KYD","Cayman Islands Dollar");
		CURRENCYID_COUNTRYNAME.put("CLP","Chilean Peso");
		CURRENCYID_COUNTRYNAME.put("CNY","Chinese Yuan");
		CURRENCYID_COUNTRYNAME.put("COP","Colombian Peso");
		CURRENCYID_COUNTRYNAME.put("KMF","Comoros Franc");
		CURRENCYID_COUNTRYNAME.put("CRC","Costa Rica Colon");
		CURRENCYID_COUNTRYNAME.put("HRK","Croatian Kuna");
		CURRENCYID_COUNTRYNAME.put("CUP","Cuban Peso");
		CURRENCYID_COUNTRYNAME.put("CYP","Cyprus Pound");
		CURRENCYID_COUNTRYNAME.put("CZK","Czech Koruna");
		CURRENCYID_COUNTRYNAME.put("DKK","Danish Krone");
		CURRENCYID_COUNTRYNAME.put("DJF","Dijibouti Franc");
		CURRENCYID_COUNTRYNAME.put("DOP","Dominican Peso");
		CURRENCYID_COUNTRYNAME.put("XCD","East Caribbean Dollar");
		CURRENCYID_COUNTRYNAME.put("EGP","Egyptian Pound");
		CURRENCYID_COUNTRYNAME.put("SVC","El Salvador Colon");
		CURRENCYID_COUNTRYNAME.put("EEK","Estonian Kroon");
		CURRENCYID_COUNTRYNAME.put("ETB","Ethiopian Birr");
		CURRENCYID_COUNTRYNAME.put("EUR","Euro");
		CURRENCYID_COUNTRYNAME.put("FKP","Falkland Islands Pound");
		CURRENCYID_COUNTRYNAME.put("GMD","Gambian Dalasi");
		CURRENCYID_COUNTRYNAME.put("GHC","Ghanian Cedi");
		CURRENCYID_COUNTRYNAME.put("GIP","Gibraltar Pound");
		CURRENCYID_COUNTRYNAME.put("XAU","Gold Ounces");
		CURRENCYID_COUNTRYNAME.put("GTQ","Guatemala Quetzal");
		CURRENCYID_COUNTRYNAME.put("GNF","Guinea Franc");
		CURRENCYID_COUNTRYNAME.put("GYD","Guyana Dollar");
		CURRENCYID_COUNTRYNAME.put("HTG","Haiti Gourde");
		CURRENCYID_COUNTRYNAME.put("HNL","Honduras Lempira");
		CURRENCYID_COUNTRYNAME.put("HKD","Hong Kong Dollar");
		CURRENCYID_COUNTRYNAME.put("HUF","Hungarian Forint");
		CURRENCYID_COUNTRYNAME.put("ISK","Iceland Krona");
		CURRENCYID_COUNTRYNAME.put("INR","Indian Rupee");
		CURRENCYID_COUNTRYNAME.put("IDR","Indonesian Rupiah");
		CURRENCYID_COUNTRYNAME.put("IQD","Iraqi Dinar");
		CURRENCYID_COUNTRYNAME.put("ILS","Israeli Shekel");
		CURRENCYID_COUNTRYNAME.put("JMD","Jamaican Dollar");
		CURRENCYID_COUNTRYNAME.put("JPY","Japanese Yen");
		CURRENCYID_COUNTRYNAME.put("JOD","Jordanian Dinar");
		CURRENCYID_COUNTRYNAME.put("KZT","Kazakhstan Tenge");
		CURRENCYID_COUNTRYNAME.put("KES","Kenyan Shilling");
		CURRENCYID_COUNTRYNAME.put("KRW","Korean Won");
		CURRENCYID_COUNTRYNAME.put("KWD","Kuwaiti Dinar");
		CURRENCYID_COUNTRYNAME.put("LAK","Lao Kip");
		CURRENCYID_COUNTRYNAME.put("LVL","Latvian Lat");
		CURRENCYID_COUNTRYNAME.put("LBP","Lebanese Pound");
		CURRENCYID_COUNTRYNAME.put("LSL","Lesotho Loti");
		CURRENCYID_COUNTRYNAME.put("LRD","Liberian Dollar");
		CURRENCYID_COUNTRYNAME.put("LYD","Libyan Dinar");
		CURRENCYID_COUNTRYNAME.put("LTL","Lithuanian Lita");
		CURRENCYID_COUNTRYNAME.put("MOP","Macau Pataca");
		CURRENCYID_COUNTRYNAME.put("MKD","Macedonian Denar");
		CURRENCYID_COUNTRYNAME.put("MGF","Malagasy Franc");
		CURRENCYID_COUNTRYNAME.put("MWK","Malawi Kwacha");
		CURRENCYID_COUNTRYNAME.put("MYR","Malaysian Ringgit");
		CURRENCYID_COUNTRYNAME.put("MVR","Maldives Rufiyaa");
		CURRENCYID_COUNTRYNAME.put("MTL","Maltese Lira");
		CURRENCYID_COUNTRYNAME.put("MRO","Mauritania Ougulya");
		CURRENCYID_COUNTRYNAME.put("MUR","Mauritius Rupee");
		CURRENCYID_COUNTRYNAME.put("MXN","Mexican Peso");
		CURRENCYID_COUNTRYNAME.put("MDL","Moldovan Leu");
		CURRENCYID_COUNTRYNAME.put("MNT","Mongolian Tugrik");
		CURRENCYID_COUNTRYNAME.put("MAD","Moroccan Dirham");
		CURRENCYID_COUNTRYNAME.put("MZM","Mozambique Metical");
		CURRENCYID_COUNTRYNAME.put("MMK","Myanmar Kyat");
		CURRENCYID_COUNTRYNAME.put("NAD","Namibian Dollar");
		CURRENCYID_COUNTRYNAME.put("NPR","Nepalese Rupee");
		CURRENCYID_COUNTRYNAME.put("ANG","Neth Antilles Guilder");
		CURRENCYID_COUNTRYNAME.put("NZD","New Zealand Dollar");
		CURRENCYID_COUNTRYNAME.put("NIO","Nicaragua Cordoba");
		CURRENCYID_COUNTRYNAME.put("NGN","Nigerian Naira");
		CURRENCYID_COUNTRYNAME.put("KPW","North Korean Won");
		CURRENCYID_COUNTRYNAME.put("NOK","Norwegian Krone");
		CURRENCYID_COUNTRYNAME.put("OMR","Omani Rial");
		CURRENCYID_COUNTRYNAME.put("XPF","Pacific Franc");
		CURRENCYID_COUNTRYNAME.put("PKR","Pakistani Rupee");
		CURRENCYID_COUNTRYNAME.put("XPD","Palladium Ounces");
		CURRENCYID_COUNTRYNAME.put("PAB","Panama Balboa");
		CURRENCYID_COUNTRYNAME.put("PGK","Papua New Guinea Kina");
		CURRENCYID_COUNTRYNAME.put("PYG","Paraguayan Guarani");
		CURRENCYID_COUNTRYNAME.put("PEN","Peruvian Nuevo Sol");
		CURRENCYID_COUNTRYNAME.put("PHP","Philippine Peso");
		CURRENCYID_COUNTRYNAME.put("PLN","Polish Zloty");
		CURRENCYID_COUNTRYNAME.put("QAR","Qatar Rial");
		CURRENCYID_COUNTRYNAME.put("ROL","Romanian Leu");
		CURRENCYID_COUNTRYNAME.put("RUB","Russian Rouble");
		CURRENCYID_COUNTRYNAME.put("WST","Samoa Tala");
		CURRENCYID_COUNTRYNAME.put("STD","Sao Tome Dobra");
		CURRENCYID_COUNTRYNAME.put("SCR","Seychelles Rupee");
		CURRENCYID_COUNTRYNAME.put("SLL","Sierra Leone Leone");
		CURRENCYID_COUNTRYNAME.put("XAG","Silver Ounces");
		CURRENCYID_COUNTRYNAME.put("SGD","Singapore Dollar");
		CURRENCYID_COUNTRYNAME.put("SKK","Slovak Koruna");
		CURRENCYID_COUNTRYNAME.put("SIT","Slovenian Tolar");
		CURRENCYID_COUNTRYNAME.put("SBD","Solomon Islands Dollar");
		CURRENCYID_COUNTRYNAME.put("SOS","Somali Shilling");
		CURRENCYID_COUNTRYNAME.put("ZAR","South African Rand");
		CURRENCYID_COUNTRYNAME.put("LKR","Sri Lanka Rupee");
		CURRENCYID_COUNTRYNAME.put("SHP","St Helena Pound");
		CURRENCYID_COUNTRYNAME.put("SDD","Sudanese Dinar");
		CURRENCYID_COUNTRYNAME.put("SRG","Surinam Guilder");
		CURRENCYID_COUNTRYNAME.put("SZL","Swaziland Lilageni");
		CURRENCYID_COUNTRYNAME.put("SEK","Swedish Krona");
		CURRENCYID_COUNTRYNAME.put("TRY","Turkey Lira");
		CURRENCYID_COUNTRYNAME.put("CHF","Swiss Franc");
		CURRENCYID_COUNTRYNAME.put("SYP","Syrian Pound");
		CURRENCYID_COUNTRYNAME.put("TWD","Taiwan Dollar");
		CURRENCYID_COUNTRYNAME.put("TZS","Tanzanian Shilling");
		CURRENCYID_COUNTRYNAME.put("THB","Thai Baht");
		CURRENCYID_COUNTRYNAME.put("TOP","Tonga Pa'anga");
		CURRENCYID_COUNTRYNAME.put("TTD","Trinidad&amp;Tobago Dollar");
		CURRENCYID_COUNTRYNAME.put("TND","Tunisian Dinar");
		CURRENCYID_COUNTRYNAME.put("TRL","Turkish Lira");
		CURRENCYID_COUNTRYNAME.put("USD","U.S. Dollar");
		CURRENCYID_COUNTRYNAME.put("AED","UAE Dirham");
		CURRENCYID_COUNTRYNAME.put("UGX","Ugandan Shilling");
		CURRENCYID_COUNTRYNAME.put("UAH","Ukraine Hryvnia");
		CURRENCYID_COUNTRYNAME.put("UYU","Uruguayan New Peso");
		CURRENCYID_COUNTRYNAME.put("VUV","Vanuatu Vatu");
		CURRENCYID_COUNTRYNAME.put("VEB","Venezuelan Bolivar");
		CURRENCYID_COUNTRYNAME.put("VND","Vietnam Dong");
		CURRENCYID_COUNTRYNAME.put("YER","Yemen Riyal");
		CURRENCYID_COUNTRYNAME.put("YUM","Yugoslav Dinar");
		CURRENCYID_COUNTRYNAME.put("ZWD","Zimbabwe Dollar");
	}

}
